clast.c: insert_guard: create correct equality guards
If the domains contains an equality

    a i_1 + b i_2 = 0

the original code would generate the guard

    if (i_2 == -a * i_1 / b)

However, -a * i_1 may not be an integer multiple of b and
so for any given value of i_2, the test could evaluate to true
for more than one value of i_1.
This happens in particular if the domain is part of
(the convex hull of a union of) a set of domains.
This patch generates the guard

    if (b * i_2 == -a * i_1)

instead, which should be safe.

diff --git a/test/makefile b/test/makefile
--- a/test/makefile
+++ b/test/makefile
@@ -248,6 +248,18 @@ test:
 		else \
 			echo "$$x passed" ; \
 	        fi ; \
+	        echo "Verify file equality (-f -1 -l 2 -override)" ; \
+		x=equality ; \
+		$(ROOT)/obj_$(TARGET)/cloog$(EXEC_SUFFIX) $$x.cloog \
+		-f -1 -l 2 -override  > ttemp ; \
+		diff -w --ignore-matching-lines='CLooG' ttemp $$x.c ; \
+		result=$$?; \
+		if [ "$$result" -eq "1" ] ; then \
+			echo "!!! Error: $$x is not the same" ; \
+			failedtest=`expr $$failedtest + 1` ; \
+		else \
+			echo "$$x passed" ; \
+	        fi ; \
 	rm ttemp ; \
 	if [ $$failedtest != 0 ] ; then \
 		echo "$$failedtest tests failed" ; \
